#!/bin/sh

#
#  STEP 2:
#  convert all tresor message strings into a binary format
#

LOCALE_RELATIVE_PATH="."

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tresor.mo" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tresor.mo" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tresor.mo.old"
	msgfmt "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tresor.po" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tresor.mo"
done
